### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by thomarse-ef** [Circuitscape/Omniscape.jl#124]
I'm not sure if this is something to do with my set up but I'm getting some unexpected results.

I've got a source surface which is mostly set to a very low number (0.0000000001) so that every cell will be included in the analysis. I've then set two cells to much higher numbers (1, 1000). I would expect much higher current around the cell that was set to 1000 (from the documentation I understand that the amperage of the target cell will be split proportionally among other source cells in the radius, while the target cell is set to ground, so there should be 1000 amps flowing into the target), but the result is about the same amount of current around each of the high value cells (about 1.998). 

Edit: I get the expected behaviour if I reduce the radius so it doesn't include the other high value cell (set `radius` in the ini to e.g. `10`)
Edit 2: the expected behaviour continues as you increase the radius up until the point where the radii of the two high value points intersect (i.e. 25 and over in below example) - really not sure why it would be doing this.

Example below, apologies it's in R not Julia:
```
library(raster)

# source
sourcer <- raster(nrows=50, ncols=100)
sourcer <- setValues(sourcer, 0.0000000001)
sourcer[cellFromRowCol(sourcer, 25, 25)] <- 1000
sourcer[cellFromRowCol(sourcer, 25, 75)] <- 1
writeRaster(sourcer, "source.asc", overwrite = TRUE)

# resistance
resistr <- raster(sourcer)
resistr <- setValues(resistr, runif(length(resistr), max = 1, min = 0))
writeRaster(resistr, "resistance_map.asc", overwrite = TRUE)

## run omniscape here ##

# view result
result <- raster("omni/cum_currmap.tif")
plot(result)

# check apms at high value source cells:
result[cellFromRowCol(result, 25, 25)]
result[cellFromRowCol(result, 25, 75)]

```

Ini file:
```
[Required]
resistance_file = resistance_map.asc
source_file = source.asc
radius = 60
block_size = 1
project_name = omni

[General options]
source_from_resistance = false
calc_flow_potential = true
calc_normalized_current = true

solver = cholmod
resistance_is_conductance = true

parallelize = true
parallel_batch_size = 30

[Output options]
write_raw_currmap = true

```

**Comment by vlandau** [comment]
Thanks for posting an issue  I'll try to take a look at this over the next couple of weeks and report back.

**Comment by vlandau** [comment]
> the expected behaviour continues as you increase the radius up until the point where the radii of the two high value points intersect (i.e. 25 and over in below example) - really not sure why it would be doing this.

In my mind this is expected. Let's call the pixel on which the moving window is centered "pixel A", and the other high source pixel "pixel B." Once the pixels A and B are contained in the same moving window, the total amount of current is determined by the strength of pixel A, and the vast majority of that current will be injected into pixel B because its strength is vastly greater than the other pixels. What this means is that essentially (ignoring the minimal impact of some current coming from the low source strength pixels) current is flowing from pixel B to pixel A. Depending on how your resistance surface looks, this will essentially mean high current flow predicted in the paths between pixels A and B.

It might help if you would share some screenshots of your outputs for the various moving window radii that you're testing.

**Comment by vlandau** [comment]
Going to close this since there haven't been any updates
