### ISSUE TITLE
Out of memory errors - advice please

### ISSUE THREAD

**Issue by joncjones** [Circuitscape/Omniscape.jl#75]
Hi - I am getting the following error:

ERROR: LoadError: OutOfMemoryError()
Stacktrace:
 [1] Array at ./boot.jl:409 [inlined]
 [2] Array at ./boot.jl:416 [inlined]
 [3] fill at ./array.jl:452 [inlined]
 [4] fill at ./array.jl:450 [inlined]
 [5] run_omniscape(::String) at ###/.julia/packages/Omniscape/ZVGgl/src/run_omniscape.jl:212
 [6] top-level scope at ###/run_trial.jl:7
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] exec_options(::Base.JLOptions) at ./client.jl:288
 [9] _start() at ./client.jl:484
in expression starting at ###/run_trial.jl:7

This job is running on a single high-performance cluster node with Intel Xeon Gold 6138 CPU (‘Sky Lake’) - 40 cores and 192GB RAM.
I am however running this on a large resistance surface - the .tif is 140MB but has 160 million cells (radius of 100 and block size 11) 
It says max vmem 112GB before it crashes out.
Ideally I do not want to reduce radius.
(Note that this is already a reduced resolution version of our data which at full res. this has 1.4 billion cells)

- am I just asking too much ? Need a bigger boat ? Is there a 'back of the envelope formula' for calculating RAM requirements ? Linked to no. cells & radius 

Apart from that, using the same settings and platform, it is successfully running landscapes with 2 million cells in 10 minutes although vmem usage is already up to 50GB 

The system only has Julia 1.4.2 so I am still running "Omniscape" => v"0.3.0"
 
Any thoughts greatly appreciated

**Comment by vlandau** [comment]
The memory usage is larger with a larger grid because Omniscape has to allocate arrays in-memory of that size. For the case with 160M cells and 40 parallel workers, to store the solves from each thread Omniscape needs to allocate 40 64-bit floating point arrays of that size, which would be would be ~ 40 * 160M * 64 bits = 51.2GB. If you're also calculating flow potential, you need an additional object of that size allocated. There are additional memory requirements requirements throughout but those are the big ones.

A good way to reduce memory usage without needing to further reduce the resolution would be to try running with fewer cores (setting the environment variable JULIA_NUM_THREADS to a value less than 40) so fewer of those arrays are allocated.

I'd like to eventually implement a version of Omniscape that doesn't need to allocate the entire arrays all at one, and instead lazily reads and writes data as it iterates through the moving window solves, but this will be a pretty big lift. I don't anticipate it being done any time soon.

I'm going to close this issue for now, but happy to continue the conversation here or in [our gitter chatroom](https://gitter.im/Circuitscape/Omniscape.jl).

If you can, I would also highly recommend upgrading to Julia 1.5.1, or you could wait to upgrade until Julia 1.6 is released.

**Comment by vlandau** [comment]
Also, I see the line that is causing the memory overflow for you is [here](https://github.com/Circuitscape/Omniscape.jl/blob/v0.3.0/src/run_omniscape.jl#L212), and you'll see that this corresponds to allocating one of those large arrays I mentioned.

**Comment by joncjones** [comment]
Thanks Vincent - your comments above might be useful pasted into Usage to guide others ? 

For my side I will both get a bigger computer and run with fewer workers and see if I can get closer to my holy grail of 20m so the connectivity layer matches the other input data layers in the final map I am working on. To do this at the national scale however means working with a grid with 1.4b cells...

all the best

J

**Comment by vlandau** [comment]
Good idea -- I can add a section "Tips for working with large resistance surfaces" or something to that effect. 

Since Omniscape solves in moving windows independently, one option for your large (1.4b pixel) problem would be to break it up into subsets (that overlap by at least 2*`radius` pixels) and solve them individually.  Then you can combine the results, taking the maximum value of inputs, to get a map for the entire area (I think Mosaic to New Raster is the tool to do this in ArcMAP).
