### ISSUE TITLE
Incorporating directional ocean currents

### ISSUE THREAD

**Issue by plthompson** [Circuitscape/Omniscape.jl#90]
Hi there, 

I'm interested in applying Omniscape/Circuitscape to model fish movement in a marine environment. I'm wondering how difficult it would be to include directional ocean currents in the analysis. Something like what was done by Dambach et al. (2016) - https://onlinelibrary.wiley.com/doi/10.1111/maec.12343 but across the entire area rather than between just a few source and target locations. As I understand it, this would require using different resistance surfaces for each source location and so I could imagine that this could be computationally intensive. Is this something that is possible within the current package or something that you would consider adding?

Thanks very much,

Patrick

**Comment by vlandau** [comment]
Omniscape currently doesn't support directional resistance graphs (i.e. where the resistance from A to B is different from the resistance from B to A), and I believe Circuitscape also doesn't, though it may in network mode (? cc @ranjanan). 

I think adding such a feature would be of general value to the connectivity modeling community. An additional example (on top of things like water currents) where this would be useful is for modelling climate connectivity (how species will track a changing climate), where uphill or northward movement is "preferred" via a lower resistance. Other examples include things like wind-driven seed dispersal or avian migration. Some evaluation would need to be done to determine feasibility with limited funding. I really like the idea though. @Kim-Hall this would be a pretty cool feature for the next round of development, eh?

@ranjanan would a directional graph be possible with Circuitscape's current solvers/framework? I guess the only difference is that the sparse graph is no longer symmetrical, but it's still just a linear solver. Supposing that the user is able to provide the directed graph (as presumably there will be difference custom code required for each specific use cases), skipping Circuitscape's conversion of the raster inputs into a graph (via `construct_graph`), it might actually be relatively straight forward...? I thinking about directed graphs as well, in the context of Circuitscape/SpatialGraphs.jl

@plthompson though this may not be immediately doable in the circuit-theoretic framework used by Circuitscape and Omniscape, you could use existing graph packages in Julia to get things like least-cost paths, random walks (or "swims" in this case!), and other metrics of connectivity such as centrality. This would require that you create a directional weighted graph "from scratch". If you had raster representations of flow direction (in radians or degrees) and strength, as well as a baseline resistance raster, then it wouldn't be terribly difficult to create a directed graph where resistance is weighted/adjusted by flow direction and strength. e.g. if currents are flowing on average from B to A, then the resistance from A to B would be made higher, and the resistance from B to A lower, and the adjustment would be larger for stronger currents. Once you have the directed graph, it's relatively easy to compute tons of different graph metrics related to connectivity.

**Comment by Kim-Hall** [comment]
@plthompson @vlandau @ranjanan -- Hi all -- I've seen some fairly simple ways of handling directionality with wall to wall Circuitscape (or what some call "omnidirectional", which I avoid because it sounds like Omniscape...).   Anyway, you could run current from one long column of "source" rasters (for example running north to south, so current would flow west to east) and have a similar column of "ground" pixels at the eastern end of the extent.   It would be simple, but if you only run the current in one direction, it's directional...maybe?  When Melissa Clark runs wall to wall Circuitscape she does this four times (all four directions) and adds them together to avoid directional bias -- so she might be able to show you an example of the four (terrestrial) maps before they are summed to see if they are actually suggesting directionality.  I've seen this basic approach used to model species invasion -- the sources are all at the edge of the invader's current edge of range, and the sinks are out in some other direction, on the opposite side of a the study extent.   More nuanced methods would for sure be interesting!   You could also try to get at a more nuanced concept through weighting outputs before adding them together -- this is something Melissa does to emphasize northern current flow, for example, in the context of climate change response.

**Comment by plthompson** [comment]
@vlandau and @Kim-Hall, thanks for your quick responses and suggestions. I think that these solutions may work for us, in particular the directional weighted graphs approach. But, I was wondering if it would be feasible to run all pairwise combinations of pixels, each time redefining resistance relative to the source. Pairwise pixels could be constrained to within a given search radius as in Omniscape (and to reduce the number of pairwise pixels).

**Comment by vlandau** [comment]
@plthompson I think Omniscape wouldn't be exactly what you want, because it simultaneously solves for current multiple sources and a given target pixel in each solve iteration. To do things truly pairwise would require some custom code that implements Circuitscape iteratively in a similar way to Omniscape. But if you were already doing that, you could presumably adjust resistance on the fly based on characteristics of the source and destination pixels.

**Comment by plthompson** [comment]
@vlandau that makes sense. I'll try to run it iteratively using Circuitscape. Thanks for your suggestions and for a great package.

**Comment by vlandau** [comment]
Always happy to help how I can! Don't hesitate to reach out if we can help along the way with clarifications, feedback, etc.

**Comment by Kim-Hall** [comment]
@plthompson we at TNC have some python scripts for deploying the Julia CS in the wall to wall method with tiles, and then stitching those tiles together.  It doesn't sound like that's the way you want to go, but just FYI.  We should probably set that whole workflow up in Julia -- each approach has different strengths.

**Comment by plthompson** [comment]
Thanks @Kim-Hall. I'm going to explore the iterative method first, but I can definitely see where the wall to wall method would work well.
